version: "1.0"
services: 
  tomcat9:
    build: C:\docker\tomcat
    networks:
      myboard:
        ipv4_address: 172.20.0.3
    restart: always
    ports: 
      - "9090:9090"
  mariadb:
    build: C:\docker\mariadb
    networks: 
      myboard: 
        ipv4_address: 172.20.0.4
    restart: always
    ports:
      - "3306:3306"
networks:
  myboard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"  